# Generated by Django 4.1.2 on 2022-11-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_event_poster_venue_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='administrator',
        ),
        migrations.AddField(
            model_name='climbuser',
            name='username',
            field=models.CharField(default='Username', max_length=50),
        ),
    ]
